#!/bin/sh

# GENERATED BY UNITY.
# DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.

# Uncomment those lines to set JVM options. This can be useful in some cases, 
# for example if you are using a JDK 9+ release. In this case, you should also
# uncomment the line on the bottom to adjust the shared memory size.
# See the issue at https://issues.gradle.org/browse/GRADLE-2509 and the comment
# at https://github.com/gradle/gradle/commit/a03c02318d373258899f1b7ac85d67bd73219ea#diff-6f4d1a5a2b04a95fa5d2a4e113b6e3d
# for more details.
# NOTE: Environment variable overrides are documented higher in this file.
#jvm_options=""
#"$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED

# Attempt to find the java executable.
JAVA_HOME="$JAVA_HOME"
if [ -z "$JAVA_HOME" ] ; then
    JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))"
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

# Find the java executable.
if [ -z "$JAVA_HOME" ] ; then
    JAVA_EXE=java
else
    JAVA_EXE="$JAVA_HOME/bin/java"
fi

if [ ! -x "$JAVA_EXE" ] ; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Find the gradle wrapper jar.
CLASSPATH="$CLASSPATH"
if [ -z "$CLASSPATH" ] ; then
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi

# Execute Gradle.
exec "$JAVA_EXE" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
